version: "3.8"

services:
  anywhat_server:
    build:
      context: "."
      dockerfile: "./cmd/server/anywhat/app.dockerfile"
    depends_on:
      - "db"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/anywhat?sslmode=disable"
    ports:
      - "9090:9090"
    env_file:
      - .env
    restart: "on-failure"

  user_server:
    build:
      context: "."
      dockerfile: "./cmd/server/user/app.dockerfile"
    depends_on:
      - "db"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/user?sslmode=disable"
    ports:
      - "9091:9091"
    env_file:
      - .env
    restart: "on-failure"

  db:
    build:
      context: "./pkg/db"
      dockerfile: "db.dockerfile"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "unless-stopped"
  