version: "3.8"

services:
  anywhat_server:
    build:
      context: "."
      dockerfile: "./cmd/server/anywhat/Dockerfile.anywhatapp"
    depends_on:
      - "db_anywhat"
    env_file:
      - .env
    restart: "on-failure"

  user_server:
    build:
      context: "."
      dockerfile: "./cmd/server/user/Dockerfile.userapp"
    depends_on:
      - "db_user"
    env_file:
      - .env
    restart: "on-failure"

  graph_server:
    build:
      context: "."
      dockerfile: "./cmd/graph/Dockerfile.graphapp"
    depends_on:
      - "anywhat_server"
      - "user_server"
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: "on-failure"

  db_anywhat:
    build:
      context: "./pkg/db/anywhat"
      dockerfile: "Dockerfile.anywhatdb"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "unless-stopped"

  db_user:
    build:
      context: "./pkg/db/user"
      dockerfile: "Dockerfile.userdb"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "unless-stopped"
  