version: "3.8"

services:
  anywhat_server:
    build:
      context: "."
      dockerfile: "./cmd/server/anywhat/app.dockerfile"
    depends_on:
      - "db_anywhat"
    ports:
      - "9090:9090"
    env_file:
      - .env
    restart: "on-failure"

  user_server:
    build:
      context: "."
      dockerfile: "./cmd/server/user/app.dockerfile"
    depends_on:
      - "db_user"
    ports:
      - "9091:9091"
    env_file:
      - .env
    restart: "on-failure"

  graph_server:
    build:
      context: "."
      dockerfile: "./cmd/graph/app.dockerfile"
    depends_on:
      - "anywhat_server"
      - "user_server"
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: "on-failure"

  db_anywhat:
    build:
      context: "./pkg/db/anywhat"
      dockerfile: "db.dockerfile"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "unless-stopped"

  db_user:
    build:
      context: "./pkg/db/user"
      dockerfile: "db.dockerfile"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "unless-stopped"
  