version: "3.8"

services:
  anywhat_server:
    build:
      context: "."
      dockerfile: "./cmd/server/app.dockerfile"
    depends_on:
      - "db"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/anywhat?sslmode=disable"
    ports:
      - "8080:8080"
    restart: "on-failure"

  user_server:
    build:
      context: "."
      dockerfile: "./cmd/server/app.dockerfile"
    depends_on:
      - "db"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/user?sslmode=disable"
    ports:
      - "8080:8080"
    restart: "on-failure"

  db:
    build:
      context: "./pkg/db"
      dockerfile: "db.dockerfile"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "unless-stopped"

  graphql:
    build:
      context: "."
      dockerfile: "./cmd/graphql/app.dockerfile"
    depends_on:
      - "server"
    ports:
      - "9090:9090"
    restart: "on-failure"
  