version: "3.8"

services:
  server:
    build:
      context: "."
      dockerfile: "./cmd/server/app.dockerfile"
    depends_on:
      - "db"
    environment:
      DATABASE_URL: "postgres://postgres:123456@db/anywhat?sslmode=disable"
    ports:
      - "8080:8080"
    restart: "on-failure"

  db:
    build:
      context: "./pkg/db"
      dockerfile: "db.dockerfile"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: "unless-stopped"
  