// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Anything struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatedAt   *string `json:"createdAt"`
	UpdatedAt   *string `json:"updatedAt"`
}

type AnythingInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatedAt   *string `json:"createdAt"`
	UpdatedAt   *string `json:"updatedAt"`
}
