// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	pb "github.com/dhanusaputra/anywhat-server/api/pb"
)

// AnywhatServer is an autogenerated mock type for the AnywhatServer type
type AnywhatServer struct {
	mock.Mock
}

// CreateAnything provides a mock function with given fields: _a0, _a1
func (_m *AnywhatServer) CreateAnything(_a0 context.Context, _a1 *pb.CreateAnythingRequest) (*pb.CreateAnythingResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.CreateAnythingResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateAnythingRequest) *pb.CreateAnythingResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CreateAnythingResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.CreateAnythingRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAnything provides a mock function with given fields: _a0, _a1
func (_m *AnywhatServer) DeleteAnything(_a0 context.Context, _a1 *pb.DeleteAnythingRequest) (*pb.DeleteAnythingResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.DeleteAnythingResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.DeleteAnythingRequest) *pb.DeleteAnythingResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.DeleteAnythingResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.DeleteAnythingRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAnything provides a mock function with given fields: _a0, _a1
func (_m *AnywhatServer) GetAnything(_a0 context.Context, _a1 *pb.GetAnythingRequest) (*pb.GetAnythingResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.GetAnythingResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetAnythingRequest) *pb.GetAnythingResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetAnythingResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetAnythingRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAnything provides a mock function with given fields: _a0, _a1
func (_m *AnywhatServer) ListAnything(_a0 context.Context, _a1 *emptypb.Empty) (*pb.ListAnythingResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.ListAnythingResponse
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty) *pb.ListAnythingResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ListAnythingResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAnything provides a mock function with given fields: _a0, _a1
func (_m *AnywhatServer) UpdateAnything(_a0 context.Context, _a1 *pb.UpdateAnythingRequest) (*pb.UpdateAnythingResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.UpdateAnythingResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.UpdateAnythingRequest) *pb.UpdateAnythingResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.UpdateAnythingResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.UpdateAnythingRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
