// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TearDownInterface is an autogenerated mock type for the TearDownInterface type
type TearDownInterface struct {
	mock.Mock
}

// Restore provides a mock function with given fields:
func (_m *TearDownInterface) Restore() {
	_m.Called()
}
